config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"
  get "/auth/login" => "auth0#login"
  get "/groceries" => "grocery_lists#show"
  get "/recipes/search" => "recipes#search"
  get "/search", to: redirect('/recipes/search')
  get "/my-recipes/cooked" => "recipes#cooked"
  get "/my-recipes/favorites" => "recipes#favorites"
  get "/my-recipes/collections" => "recipes#collections"
  get "/recipes/ingredient/:ingredient" => "recipes#ingredient"
  get '/add-to-collection' => "collections#add_to_collection"
  get '/remove-from-collection' => "collections#remove_from_collection"
  get '/about', to: "pages#about"
  get '/press', to: "pages#press"
  get '/for-blogs', to: "pages#for_blogs"
  get '/import', to: "recipes#import"

  resources :recipe_sources, path: :sources do
    resources :recipes
  end

  resources :collections

  resources :recipes do
    resources :meal_plans
    resources :likes

    member do
      get "/unlike", to: "recipes#unlike"
      get "/like", to: "recipes#like"
      get '/add-to-list', to: "recipes#add_to_list"
      get '/remove-from-list', to: "recipes#remove_from_list"
    end
  end

  resources :meal_plans do
    member do
      get "archive", to: "meal_plans#archive"
    end
  end
  root :to => "recipes#index"
end

app/controllers/grocery_lists_controller.rb
class GroceryListsController < ApplicationController
  after_action :store_location, only: [:show]

  def show
    ingredient_count
    grocery_items_on_list
  end
end

app/helpers/grocery_lists_helper.rb
module GroceryListsHelper
  def is_current_recipe_on_list
    if current_user
      @recipe = Recipe.friendly.find(params[:id])
      if MealPlan.where(recipe_id: @recipe.id, status: "Upcoming", user_id: current_user["uid"]).count > 0
        @meal_plan = MealPlan.where(recipe_id: @recipe.id, status: "Upcoming", user_id: current_user["uid"]).first
        @already_added = true;
      end
    end
  end

  def grocery_items_on_list
    # get all recipes on list
    @recipes = Recipe.joins(:meal_plans).where(meal_plans: {user_id: current_user["uid"], status: "Upcoming"})

    # get all ingredients from all recipes on list
    @ingreds = Ingredient.where('recipe_id IN (?)', @recipes.select { |r| r.id })

    # group ingredients by grocery item
    @grocery_item_grouping = @ingreds.group_by{ |i| i.grocery_item }

    # group ingredients by recipes
    @recipe_grouping = @ingreds.group_by{ |i| i.recipe }
  end
end

app/views/grocery_lists/show.html.erb
<div class="hero hero--groceries">
  <div class="grocery-list-header">
    <h1>Groceries</h1>
    <div class="ingredient-count">
      <span id="checked-items">0</span>
      of
      <span id="total-items"><%= @ingredient_count %></span>
    </div>
  </div>
</div>
<div class="container container--recipe">
  <p id="grouping-toggle">Group by:
    <a href="#" id="js-group-by-recipe" class="simple-link simple-link--underline">Recipe</a>
    <a href="#" id="js-group-by-item" class="simple-link simple-link--underline">Item</a>
  </p>
</div>
<div class="container container--recipe">
  <div id="recipe-grouping" class="grocery-list-section">
    <% @recipe_grouping.each do |recipe, ingreds| %>
      <div class="ingredient-group ingredient-group--meal-plan">
        <div class="recipe__banner">
          <div class="recipe__image">
            <% unless recipe.image_url.blank? %>
              <%= image_tag recipe.image_url %>
            <% else %>
              <%= image_tag "default-landscape.png" %>
            <% end %>
          </div>
          <div>
            <%= link_to recipe_source_recipe_path(recipe.recipe_source_id ,recipe, false) do %>
              <h2><%= recipe.name %></h2>
            <% end %>
            <%= link_to "Remove", remove_from_list_recipe_path(recipe.meal_plans.active(@current_user).first), class: "simple-link simple-link--underline" %>
          </div>
        </div>
        <% if ingreds.count > 0 %>
          <% ingreds.each do |ingred| %>
            <div class="ingredient ingredient--checkable" data-ingredient="<%= ingred.id %>">
              <div class="checkbox"></div>
              <p><%= ingred.note %></p>
            </div>
          <% end %>
        <% else %>
          <% recipe.ingredients_array.each do |ingred| %>
            <div class="ingredient ingredient--checkable" data-ingredient="<%= ingred.id %>">
              <div class="checkbox"></div>
              <p><%= ingred %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div id="grocery-item-grouping" class="grocery-list-section grocery-list-section--hidden">
    <h2>Grocery Items</h2>
    <% @grocery_item_grouping.each do |item, ingreds| %>
      <div class="ingredient ingredient--checkable ingredient--grocery">
        <div class="checkbox"></div>
        <div class="grocery-item-container">
          <p class="grocery-item"><%= item.name %></p>
          <% ingreds.each do |ingred| %>
            <div class="ingred" data-ingredient="<%= ingred.id %>">
              <p class="ingred__content">
                <span class="ingred__note"><%= ingred.note %></span>
                <span class="ingred__recipe"><%= ingred.recipe.name %></span>
              </p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  function incrementCount(el) {
    var checkedIngredients = $('#checked-items').text();
    if ($(el).hasClass('ingredient--checked')) {
      checkedIngredients--
    } else {
      checkedIngredients++
    }
    $(el).toggleClass('ingredient--checked');
    $('#checked-items').text(checkedIngredients);
  }

  $('#grocery-item-grouping .ingredient').on('click', function() {
    alreadyChecked = false;
    if ($(this).hasClass('ingredient--checked')) {
      alreadyChecked = true;
    }
    $(this).find('.ingred').each(function() {
      id = $(this).attr("data-ingredient")
      if (alreadyChecked == true) {
        $("#recipe-grouping").find(`[data-ingredient='${id}']`).removeClass('ingredient--checked');
      } else {
        $("#recipe-grouping").find(`[data-ingredient='${id}']`).addClass('ingredient--checked');
      }
    })

    el = $(this)
    incrementCount(el)
  })

  $('#recipe-grouping .ingredient').on('click', function() {
    alreadyChecked = false;
    if ($(this).hasClass('ingredient--checked')) {
      alreadyChecked = true;
    }
    id = $(this).attr("data-ingredient")
    if (alreadyChecked == true) {
      $("#grocery-item-grouping").find(`[data-ingredient='${id}']`).removeClass('ingredient--checked');
      $("#grocery-item-grouping").find(`[data-ingredient='${id}']`).closest('.ingredient').removeClass('ingredient--checked');
    } else {
      $("#grocery-item-grouping").find(`[data-ingredient='${id}']`).addClass('ingredient--checked');
    }

    el = $(this)
    incrementCount(el)
  })

  function updateCount(group) {
    checked = $(group + ' .ingredient.ingredient--checked').length
    $('#checked-items').text(checked)

    total = $(group + ' .ingredient').length
    $('#total-items').text(total)
  }

  $('#js-group-by-recipe').on('click', function(e) {
    e.preventDefault()
    $('#recipe-grouping').removeClass('grocery-list-section--hidden')
    $('#grocery-item-grouping').addClass('grocery-list-section--hidden')
    updateCount('#recipe-grouping')
  })

  $('#js-group-by-item').on('click', function(e) {
    e.preventDefault()
    $('#grocery-item-grouping').removeClass('grocery-list-section--hidden')
    $('#recipe-grouping').addClass('grocery-list-section--hidden')
    updateCount('#grocery-item-grouping')
  })
</script>