config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"
  get "/auth/login" => "auth0#login"
  get "/groceries" => "grocery_lists#show"
  get "/recipes/search" => "recipes#search"
  get "/search", to: redirect('/recipes/search')
  get "/my-recipes/cooked" => "recipes#cooked"
  get "/my-recipes/favorites" => "recipes#favorites"
  get "/my-recipes/collections" => "recipes#collections"
  get "/recipes/ingredient/:ingredient" => "recipes#ingredient"
  get '/add-to-collection' => "collections#add_to_collection"
  get '/remove-from-collection' => "collections#remove_from_collection"
  get '/about', to: "pages#about"
  get '/press', to: "pages#press"
  get '/for-blogs', to: "pages#for_blogs"
  get '/import', to: "recipes#import"

  resources :recipe_sources, path: :sources do
    resources :recipes
  end

  resources :collections

  resources :recipes do
    resources :meal_plans
    resources :likes

    member do
      get "/unlike", to: "recipes#unlike"
      get "/like", to: "recipes#like"
      get '/add-to-list', to: "recipes#add_to_list"
      get '/remove-from-list', to: "recipes#remove_from_list"
    end
  end

  resources :meal_plans do
    member do
      get "archive", to: "meal_plans#archive"
    end
  end
  root :to => "recipes#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_save :scrape_recipe
  after_save :save_ingredients

  belongs_to :recipe_source
  has_many :meal_plans, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :ingredients, :dependent => :destroy
  has_many :grocery_items, through: :ingredients
  has_and_belongs_to_many :collections

  accepts_nested_attributes_for :meal_plans
  accepts_nested_attributes_for :likes
  accepts_nested_attributes_for :ingredients
  validates_length_of :ingredients_array, minimum: 1, if: :scrape_recipe
  validates_presence_of :name, if: :scrape_recipe

  paginates_per 24

  extend FriendlyId
  friendly_id :name, use: :slugged

  def scrape_recipe
    require 'open-uri'
    require 'mechanize'
    require 'aws-sdk-s3'
    agent = Mechanize.new

    self.link = self.link.split('?').first

    identify_recipe_source

    unless @recipe_source.blank?
      save_recipe_name
      scrape_ingredient_array
      unless @recipe_source.scrape_image.blank?
        unless @doc.css(@recipe_source.scrape_image).blank?
          if @doc.css(@recipe_source.scrape_image).first.attr('src')
            i = @doc.css(@recipe_source.scrape_image).first.attr('src')
            save_image_to_s3(i, agent)
          elsif @doc.css(@recipe_source.scrape_image).first.attr('srcset')
            i = @doc.css(@recipe_source.scrape_image).first.attr('srcset')
            i = i.split('.jpg')
            i = i[0] + '.jpg'
            save_image_to_s3(i, agent)
          end
        end
      end
    else
      false
    end
  end

  def identify_recipe_source
    @doc = Nokogiri::HTML(open(self.link, 'User-Agent' => 'firefox'))
    s = URI.parse(self.link)
    domain_segments = s.host.split('.')
    if domain_segments.count > 2
      domain = domain_segments[1] + "." + domain_segments[2]
    else
      domain = s.host
    end
    @recipe_source = RecipeSource.where(domain: domain).first
  end

  def save_recipe_name
    if @doc.css(@recipe_source.scrape_name).first
      self.name = @doc.css(@recipe_source.scrape_name).first.text.downcase
    end
  end

  def scrape_ingredient_array
    self.ingredients_array = []
    ingredients = @doc.css(@recipe_source.scrape_ingredient)
    ingredients.each do |ingredient|
      self.ingredients_array << ingredient.text
    end
  end

  def save_ingredients
    @doc = Nokogiri::HTML(open(self.link, 'User-Agent' => 'firefox'))
    ingredients = @doc.css(@recipe_source.scrape_ingredient)
    ingredients.each do |ingredient|
      self.ingredients_array << ingredient.text.downcase
      grocery_item_name = set_grocery_item(ingredient.text)
      unless grocery_item_name.blank?
        grocery_item = GroceryItem.where(name: grocery_item_name).first_or_create(name: grocery_item_name)
      else
        grocery_item = GroceryItem.where(name: "Unidentified").first_or_create(name: "Unidentified")
      end
      ing = Ingredient.where(recipe_id: self.id, note: ingredient.text).first_or_create(recipe_id: self.id, grocery_item_id: grocery_item.id, note: ingredient.text)
    end
  end

  def set_grocery_item(string)
    require "google/cloud/language"
    language = Google::Cloud::Language.new
    response = language.analyze_entities content: string, type: :PLAIN_TEXT
    entities = response.entities
    blacklist = ["cup", "teaspoon", "pinch", "tablespoon"]
    unless entities.blank?
      entities.each do |e|
        return e.name unless blacklist.include?(e.name.downcase)
      end
    end
    return nil
  end

  def save_image_to_s3(i, agent)
    slug = self.name.parameterize
    if i[0] === "/" && i[1] === "/"
      i = "https:" + i
    end
    agent.get(i).save "tmp/cache/assets/images/#{slug}.jpg"
    s3 = Aws::S3::Resource.new(region:'us-east-1')
    obj_key = "recipes/#{@recipe_source.slug}/#{slug}"
    obj = s3.bucket('recidex').object(obj_key)
    obj.upload_file("tmp/cache/assets/images/#{slug}.jpg")
    bucket = s3.bucket("recidex")
    object = bucket.object(obj_key)
    resp = object.acl.put({ acl: "public-read" })
    self.image_url = "https://s3.amazonaws.com/recidex/#{obj_key}"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :likes, only: [:show, :index, :search, :favorites, :cooked, :collections, :ingredient]
  before_action :authenticate_user!, only: [:like, :add_to_list, :import]
  before_action :is_admin?, only: [:edit, :update, :destroy]
  after_action :store_location, only: [:show]

  def index
    @recipes = Recipe.all.order("created_at DESC").page params[:page]
    @recipe = Recipe.new
    @random_recipe = Recipe.order('random()').first
  end

  def show
    @meal_plans = @recipe.meal_plans
    if current_user
      @like = Like.where(recipe_id: @recipe.id, user_id: current_user["uid"]).first
    end
    @recipe_source = RecipeSource.friendly.find(@recipe.recipe_source.id)
    is_current_recipe_on_list
    people_also_liked
    related_recipes(@recipe)
  end

  def import
    create
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create(link = nil)
    @recipe = Recipe.where(link: recipe_params[:link]).first
    identify_recipe_source

    if @recipe.present? && @recipe_source.present?
      like_this_recipe
      redirect_to recipe_source_recipe_path(@recipe_source, @recipe)
    elsif @recipe_source.present?
      @recipe = @recipe_source.recipes.build(params[:recipe].permit(:name, :link, :ingredients, :image_url))
      respond_to do |format|
        if @recipe && @recipe.save
          format.html { redirect_to recipe_source_recipe_path(@recipe_source, @recipe), notice: 'Recipe was successfully created.' }
          format.json { render :show, status: :created, location: @recipe }
          like_this_recipe
        else
          recipe_info = {
            pretext: "Someone tried (unsuccessfully) to create a recipe.",
            title: "#{recipe_params[:link]}",
            title_link: "#{recipe_params[:link]}",
            color: "#5a4753",
          }
          RECIPE_NOTIFIER.ping(attachments: [recipe_info])
          format.html { redirect_to recipes_url, notice: "Bummer. That link didn't seem to work :/."}
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        recipe_info = {
          pretext: "Someone tried using a new recipe source.",
          title: "#{recipe_params[:link]}",
          title_link: "#{recipe_params[:link]}",
          color: "#5a4753",
        }
        RECIPE_NOTIFIER.ping(attachments: [recipe_info])
        format.html { redirect_to recipes_url, notice: "Sorry, we don't support this blog or website yet. We've recorded your link and will have it working soon."}
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.'}
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @recipe = Recipe.friendly.find(params[:id])
    @like = @recipe.likes.where(recipe_id: @recipe.id, user_id: current_user["uid"]).first_or_create(user_id: current_user["uid"])
    if params[:login]
      respond_to do |format|
        format.html { redirect_to recipe_source_recipe_path(@recipe.recipe_source, @recipe), notice: "Howdy, welcome back! Let's get cooking." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def unlike
    @recipe = Recipe.friendly.find(params[:id])
    @like = @recipe.likes.where(user_id: current_user["uid"]).first
    @like.destroy
    respond_to do |format|
      format.html
      format.js
    end
  end

  def add_to_list
    @recipe = Recipe.friendly.find(params[:id])
    @meal_plan = @recipe.meal_plans.create(recipe_id: @recipe.id, user_id: current_user["uid"], status: "Upcoming")
    redirect_to recipe_source_recipe_path(@recipe.recipe_source, @recipe)
  end

  def remove_from_list
    @meal_plan = MealPlan.find(params[:id])
    @meal_plan.update_column(:status, "Complete")
    @meal_plan.save
    @recipe = Recipe.find(@meal_plan.recipe_id)
    redirect_to session[:user_return_to] || root_path
  end

  def search
    @recipe = Recipe.new
    if params[:term]
      @term = params[:term]
      @term = @term.downcase.tr("-", " ")
      @results = Recipe.where("lower(name) like ?", "%#{@term}%")
      @recipes = @results.page params[:page]
    else
      @recipes = Recipe.all.page params[:page]
    end
  end

  def favorites
    previously_cooked
  end

  def collections
    previously_cooked
  end

  def cooked
    previously_cooked
  end

  def ingredient
    @recipes = Recipe.joins(:grocery_items)
      .where("grocery_items.name = ?", params[:ingredient])
      .group('recipes.id')
      .page params[:page]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(
        :name, :link, :ingredients_array, :image_url,
        meal_plans_params: [:recipe_id, :user_id, :status],
        likes_params: [:recipe_id, :user_id],
        ingredients_params: [:recipe_id, :grocery_item_id, :qty, :measurement, :note, :aisle]
      )
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def previously_cooked
    if current_user
      meal_plans = MealPlan.where(user_id: current_user["uid"], status: "Complete")
      @previously_cooked = Set[]
      meal_plans.each do |meal_plan|
        @previously_cooked.add(Recipe.find(meal_plan.recipe_id))
      end
    end
  end

  def people_also_liked
    other_likers = []
    Like.where(recipe_id: @recipe.id).each do |like|
      if current_user
        other_likers.push(like.user_id) unless like.user_id == current_user["uid"]
      else
        other_likers.push(like.user_id)
      end
    end

    @people_also_liked = []
    other_likers.each do |user_id|
      Like.where(user_id: user_id).each do |like|
        @people_also_liked.push(Recipe.find(like.recipe_id)) unless like.recipe_id == @recipe.id
      end
    end
  end

  def related_recipes(r)
    terms = r.name.split(" ")
    excluded_terms = ["and"]
    terms = terms.map(&:capitalize) - excluded_terms.map(&:capitalize)
    @related_recipes = []
    terms.each do |term|
      recs = Recipe.where("name like ?", "%#{term}%")
      recs.each do |rec|
        @related_recipes.push(rec) unless rec.name == r.name || @related_recipes.include?(rec)
      end
    end
  end

  def like_this_recipe
    if current_user
      like = @recipe.likes.where(recipe_id: @recipe.id, user_id: current_user["uid"]).first || @recipe.likes.build(recipe_id: @recipe.id, user_id: current_user["uid"])
      like.save
    end
  end

  def recipe_search(term)
    return Recipe.where("name like ?", "%#{term}%")
  end

  def identify_recipe_source
    s = URI.parse(recipe_params[:link])
    domain_segments = s.host.split('.')
    if domain_segments.count > 2
      domain = domain_segments[1] + "." + domain_segments[2]
    else
      domain = s.host
    end
    @recipe_source = RecipeSource.where(domain: domain).first
  end
end

app/views/recipes/_collection_recipe_card.html.erb
<div class="recipe-card-container">
  <%= link_to recipe_source_recipe_path(recipe_source, recipe), class: "recipe-card--large" do %>
    <% unless recipe.image_url.blank? %>
      <div class="recipe-card__image" style="background-image: url(<%= recipe.image_url %>)"></div>
    <% else %>
      <div class="recipe-card__image" style="background-image: url(<%= asset_path 'default-portrait.png' %>) "></div>
    <% end %>
    <h3><%= recipe.name %></h3>
    <% if show_source == true %>
      <p class="minor"><%= recipe_source.name %></p>
    <% end %>
  <% end %>
  <div class="remove-from-collection-container">
    <% if current_user && current_user["uid"] === @collection.user_id %>
      <%= link_to remove_from_collection_path(recipe: recipe, collection: @collection), class: "recipe-card__like like" do %>
        <i class="trash icon"></i>
      <% end %>
    <% end %>
  </div>
  <div class="like-container">
    <% if current_user && @likes.include?(recipe) %>
      <%= render 'recipes/unlike', recipe: recipe %>
    <% else %>
      <%= render 'recipes/like', recipe: recipe %>
    <% end %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <div class="ui large input">
    <%= form.text_field :link, id: :recipe_link, placeholder: "Paste a recipe link" %>
  </div>
  <button class="ui icon button" type="submit">
    <i class="arrow right icon"></i>
  </button>
<% end %>

app/views/recipes/_my_recipes_nav.html.erb
<div class="my-recipes-nav">
  <%= link_to "#{@likes.count} Favorites", my_recipes_favorites_path, class: "simple-link simple-link--background" %>
  <%= link_to "#{@previously_cooked.count} Previously Cooked", my_recipes_cooked_path, class: "simple-link simple-link--background" %>
  <%= link_to "#{@my_collections.count} Collections", my_recipes_collections_path, class: "simple-link simple-link--background" %>
</div>

app/views/recipes/_recipe_card_large.html.erb
<div class="recipe-card-container">
  <%= link_to recipe_source_recipe_path(recipe_source, recipe), class: "recipe-card--large" do %>
    <% unless recipe.image_url.blank? %>
      <div class="recipe-card__image" style="background-image: url(<%= recipe.image_url %>)"></div>
    <% else %>
      <div class="recipe-card__image" style="background-image: url(<%= asset_path 'default-portrait.png' %>) "></div>
    <% end %>
    <h3><%= recipe.name %></h3>
    <% if show_source == true %>
      <p class="minor"><%= recipe_source.name %></p>
    <% end %>
  <% end %>
  <div class="like-container">
    <% if current_user && @likes.include?(recipe) %>
      <%= render 'recipes/unlike', recipe: recipe %>
    <% else %>
      <%= render 'recipes/like', recipe: recipe %>
    <% end %>
  </div>
</div>

app/views/recipes/collections.html.erb
<div class="hero hero--recipe-source">
  <h1>My Recipes</h1>
</div>
<div class="container my-recipes-container">
  <%= render 'my_recipes_nav' %>
  <div class="my-recipes__grid">
    <h2>My Collections</h2>
    <div class="recipes-grid collections">
      <% @my_collections.each do |c| %>
        <div class="flex-item collection-card">
          <div class="collection-card__title">
            <%= link_to c do %>
              <h3><%= c.name %></h3>
            <% end %>
            <%= link_to "All Recipes", c, class: "simpe-link simple-link--underline" %>
          </div>
          <% c.recipes.limit(3).each do |recipe| %>
            <%= link_to recipe_source_recipe_path(recipe.recipe_source, recipe) do %>
              <div class="recipe__banner">
                <div class="recipe__image">
                  <% unless recipe.image_url.blank? %>
                    <%= image_tag recipe.image_url %>
                  <% else %>
                    <%= image_tag "default-landscape.png" %>
                  <% end %>
                </div>
                <div class="recipe__title">
                  <h4 class="recipe__name"><%= recipe.name %></h4>
                  <p class="minor"><%= recipe.recipe_source.name %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/cooked.html.erb
<div class="hero hero--recipe-source">
  <h1>My Recipes</h1>
</div>
<div class="container my-recipes-container">
  <%= render 'my_recipes_nav' %>
  <div class="my-recipes__grid">
    <h2>Previously Cooked</h2>
    <div class="recipes-grid">
      <% @previously_cooked.each do |recipe| %>
        <%= render 'recipes/recipe_card_large', recipe: recipe, recipe_source: recipe.recipe_source, show_source: false %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/favorites.html.erb
<div class="hero hero--recipe-source">
  <h1>My Recipes</h1>
</div>
<div class="container my-recipes-container">
  <%= render 'my_recipes_nav' %>
  <div class="my-recipes__grid">
    <h2>Favorites</h2>
    <div class="recipes-grid">
      <% @likes.each do |recipe| %>
        <%= render 'recipes/recipe_card_large', recipe: recipe, recipe_source: recipe.recipe_source, show_source: false %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="hero hero--home">
  <h1>Save all of your favorite recipes in one place.</h1>
</div>
<div class="container container--recipe-index">
  <div class="sidebar">
    <section>
      <h4>Most Popular Blogs</h4>
      <ul>
        <% @most_popular_sources.each do |source| %>
          <li><%= link_to source.name, recipe_source_path(source), class: "simple-link simple-link--underline" %></li>
        <% end %>
      </ul>
    </section>
    <section>
      <h4>Recently Added</h4>
      <ul>
        <% @new_sources.each do |source| %>
          <li><%= link_to source.name, recipe_source_path(source), class: "simple-link simple-link--underline" %></li>
        <% end %>
      </ul>
    </section>
    <section>
      <h4>Diets</h4>
      <ul>
        <li><%= link_to "Gluten-Free", recipes_search_path(term: "gluten-free"), class: "simple-link simple-link--underline" %></li>
        <li><%= link_to "Keto", recipes_search_path(term: "keto"), class: "simple-link simple-link--underline" %></li>
        <li><%= link_to "Paleo", recipes_search_path(term: "paleo"), class: "simple-link simple-link--underline" %></li>
        <li><%= link_to "Vegan", recipes_search_path(term: "vegan"), class: "simple-link simple-link--underline" %></li>
        <li><%= link_to "Vegetarian", recipes_search_path(term: "vegetarian"), class: "simple-link simple-link--underline" %></li>
      </ul>
    </section>
    <section>
      <h4>Popular Ingredients</h4>
      <ul>
        <li><%= link_to "Beef", "/recipes/ingredient/beef", class: "simple-link simple-link--underline" %></li>
        <li><%= link_to "Chicken", "/recipes/ingredient/chicken", class: "simple-link simple-link--underline" %></li>
        <li><%= link_to "Chocolate", "/recipes/ingredient/chocolate", class: "simple-link simple-link--underline" %></li>
        <li><%= link_to "Kale", "/recipes/ingredient/kale", class: "simple-link simple-link--underline" %></li>
        <li><%= link_to "Noodles", "/recipes/ingredient/noodles", class: "simple-link simple-link--underline" %></li>
      </ul>
    </section>
    <section>
      <h4>Feeling lucky?</h4>
      <ul>
        <li><%= link_to "Random Recipe", recipe_source_recipe_path(@random_recipe.recipe_source, @random_recipe), class: "simple-link simple-link--underline" %></li>
      </ul>
    </section>
  </div>
  <div class="recipes-grid">
    <% @recipes.each do |recipe| %>
      <%= render 'recipe_card_large', recipe: recipe, recipe_source: recipe.recipe_source, show_source: true %>
    <% end %>
  </div>
</div>
<div class="pagination-wrapper">
  <%= paginate @recipes, window: 1 %>
</div>

app/views/recipes/ingredient.html.erb
<div class="hero hero--recipe">
  <div class="hero__content">
    <div class="recipe__header">
      <h1 itemprop="name">The most popular recipes using <%= params[:ingredient] %></h1>
    </div>
  </div>
</div>
<div class="container container--recipe">
  <% unless @recipes.first.image_url.blank? %>
    <div class="recipe__image">
      <%= image_tag @recipes.first.image_url %>
    </div>
  <% end %>
</div>
<div class="container">
  <div class="my-recipes__grid">
    <div class="recipes-grid">
      <% @recipes.each do |recipe| %>
        <%= render 'recipes/recipe_card_large', recipe: recipe, recipe_source: recipe.recipe_source, show_source: true %>
      <% end %>
    </div>
  </div>
  <div class="pagination-wrapper">
    <%= paginate @recipes, window: 1 %>
  </div>
</div>

app/views/recipes/like.js.erb
$('.like').bind('ajax:success', function(){
  $(this).closest('.like').hide();
  $(this).closest('.like-container').html('<%= escape_javascript (render partial: 'unlike', recipe: @recipe ) %>');
});

app/views/recipes/new.html.erb
<div class="container">
  <div class="hero hero--home">
    <div class="hero__copy">
      <h1>Paste a recipe link from your favorite blog.</h1>
      <p>Recidex can import recipes from over 100 different websites.</p>
    </div>
    <%= render 'form', recipe: @recipe %>
  </div>
</div>

app/views/recipes/search.html.erb
<div class="container container--search">
  <div class="search-inputs">
    <div class="search-by-term">
      <% if @term && @term.present? %>
        <h2>Showing results for "<span class="search-input__term"><%= @term %></span>" (<%= @results.count %>)</h2>
      <% else %>
        <h2>Search over 5,000 recipes</h2>
      <% end %>
      <%= render 'search_form' %>
    </div>
  </div>
  <div class="search-results">
    <div class="results">
      <% @recipes.each do |recipe| %>
        <%= render 'recipe_card_large', recipe: recipe, recipe_source: recipe.recipe_source, show_source: true %>
      <% end %>
    </div>
    <div class="pagination-wrapper">
      <%= paginate @recipes, window: 1 %>
    </div>
  </div>
</div>

app/views/recipes/unlike.js.erb
$('.unlike').bind('ajax:success', function(){
  $(this).closest('.unlike').hide();
  $(this).closest('.like-container').html('<%= escape_javascript (render partial: 'like', recipe: @recipe ) %>');
});