config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"
  get "/auth/login" => "auth0#login"
  get "/groceries" => "grocery_lists#show"
  get "/recipes/search" => "recipes#search"
  get "/search", to: redirect('/recipes/search')
  get "/my-recipes/cooked" => "recipes#cooked"
  get "/my-recipes/favorites" => "recipes#favorites"
  get "/my-recipes/collections" => "recipes#collections"
  get "/recipes/ingredient/:ingredient" => "recipes#ingredient"
  get '/add-to-collection' => "collections#add_to_collection"
  get '/remove-from-collection' => "collections#remove_from_collection"
  get '/about', to: "pages#about"
  get '/press', to: "pages#press"
  get '/for-blogs', to: "pages#for_blogs"
  get '/import', to: "recipes#import"

  resources :recipe_sources, path: :sources do
    resources :recipes
  end

  resources :collections

  resources :recipes do
    resources :meal_plans
    resources :likes

    member do
      get "/unlike", to: "recipes#unlike"
      get "/like", to: "recipes#like"
      get '/add-to-list', to: "recipes#add_to_list"
      get '/remove-from-list', to: "recipes#remove_from_list"
    end
  end

  resources :meal_plans do
    member do
      get "archive", to: "meal_plans#archive"
    end
  end
  root :to => "recipes#index"
end

app/views/shared/_add_to_collection_modal.html.erb
<div class="ui modal add-to-collection-modal">
  <div class="recipe__banner">
    <div class="recipe__image">
      <% unless recipe.image_url.blank? %>
        <%= image_tag recipe.image_url %>
      <% else %>
        <%= image_tag "default-landscape.png" %>
      <% end %>
    </div>
    <div class="recipe__title">
      <h2 class="recipe__name"><%= recipe.name %></h2>
      <p class="minor"><%= recipe.recipe_source.name %></p>
    </div>
  </div>
  <div class="lists">
    <% if @my_collections.count > 0 %>
      <h2>Choose Collection</h2>
      <ul class="collection-list">
        <% @my_collections.each do |c| %>
          <%= link_to add_to_collection_path(recipe: recipe, collection: c), class: "add-to-list-link", remote: true do %>
            <li><%= c.name %></li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <h2>Create A Collection</h2>
      <p>Collections make it easy for you to organize recipes however you'd like. Collect your favorite breakfast recipes, vegetarian recipes, or anything else you'd like!</p>
    <% end %>
    <a href="#" class="simple-link simple-link--underline simple-link--small" id="new-collection-link">+ Create New Collection</a>
    <%= form_with model: @collection, local: true, id: "new-collection-form", class: "d-none" do |form| %>
      <div class="ui small input">
        <%= form.text_field :name, placeholder: "Collection name" %>
      </div>
      <%= form.hidden_field :recipe, value: recipe.id %>
      <button class="simple-link simple-link--secondary simple-link--block" type="submit">
        Add
      </button>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#new-collection-link').on('click', function(e) {
    e.preventDefault();
    $(this).hide();
    $('#new-collection-form').removeClass('d-none');
    $('#new-collection-form .ui.input input').focus();
  })

  $('.ui.modal')
    .modal('attach events', '.add-to-list-link', 'hide')
  ;

  $('#new-collection-form').on('submit', function() {
    $('.ui.modal')
      .modal('hide')
    ;
  })
</script>

app/views/shared/_footer.html.erb
<footer class="container">
  <section>
    <h4>Connect</h4>
    <ul>
      <li><%= link_to "About Recidex", about_path, class: "simple-link simple-link--underline" %></li>
      <li><%= link_to "For Blogs (BETA)", for_blogs_path, class: "simple-link simple-link--underline" %></li>
      <li><%= link_to "Press", press_path, class: "simple-link simple-link--underline" %></li>
      <li><%= link_to "Facebook", "https://www.facebook.com/recidex", class: "simple-link simple-link--underline" %></li>
      <li><%= link_to "Twitter", "https://twitter.com/my_recidex", class: "simple-link simple-link--underline" %></li>
    </ul>
  </section>
  <section>
    <h4>Most Popular Blogs</h4>
    <ul>
      <% @most_popular_sources.each do |source| %>
        <li><%= link_to source.name, recipe_source_path(source), class: "simple-link simple-link--underline" %></li>
      <% end %>
    </ul>
  </section>
  <section>
    <h4>Most Popular Recipes</h4>
    <ul>
      <% @most_popular_recipes.each do |recipe| %>
        <li><%= link_to recipe.name, recipe_source_recipe_path(recipe.recipe_source, recipe), class: "simple-link simple-link--underline" %></li>
      <% end %>
    </ul>
  </section>
</footer>

app/views/shared/_mobile_nav_links.html.erb
<%= link_to "Search Recipes", recipes_search_path, class: "simple-link simple-link--background simple-link--uppercase" %>
<%= link_to "Import A Recipe", new_recipe_path, class: "simple-link simple-link--background simple-link--uppercase" %>
<% if current_user %>
  <%= link_to "Groceries(#{@ingredient_count})", groceries_path, class: "simple-link simple-link--background simple-link--uppercase" %>
  <%= link_to "My Recipes", my_recipes_favorites_path, class: "simple-link simple-link--uppercase" %>
  <%= link_to "My Collections", my_recipes_collections_path, class: "simple-link simple-link--uppercase" %>
  <%= link_to "Logout", auth_logout_path, class: "simple-link simple-link--uppercase" %>
<% else %>
  <%= link_to "Sign In", {controller: "auth0", action: "login", redirect_url: request.original_url }, class: "simple-link simple-link--background simple-link--uppercase" %>
<% end %>

app/views/shared/_nav_links.html.erb
<%= link_to "Import A Recipe", new_recipe_path, class: "simple-link simple-link--background simple-link--uppercase" %>
<% if current_user %>
  <%= link_to "Groceries(#{@ingredient_count})", groceries_path, class: "simple-link simple-link--background simple-link--uppercase m-hidden" %>
  <div class="ui top right pointing dropdown item nav-avatar m-hidden">
    <% if current_user["info"]["image"] %>
      <%= image_tag current_user["info"]["image"] %>
    <% else %>
      <%= image_tag "avatar.svg" %>
    <% end %>
    <ul class="menu">
      <li class="item"><%= link_to "My Recipes", my_recipes_favorites_path, class: "simple-link simple-link--uppercase" %></li>
      <li class="item"><%= link_to "My Collections", my_recipes_collections_path, class: "simple-link simple-link--uppercase" %></li>
      <li class="item"><%= link_to "Logout", auth_logout_path, class: "simple-link simple-link--uppercase" %></li>
    </ul>
  </div>
<% else %>
  <%= link_to "Sign In", {controller: "auth0", action: "login", redirect_url: request.original_url }, class: "simple-link simple-link--background simple-link--uppercase" %>
<% end %>

<script type="text/javascript">
  $('.ui.dropdown')
    .dropdown()
  ;
</script>