config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"
  get "/auth/login" => "auth0#login"
  get "/groceries" => "grocery_lists#show"
  get "/recipes/search" => "recipes#search"
  get "/search", to: redirect('/recipes/search')
  get "/my-recipes/cooked" => "recipes#cooked"
  get "/my-recipes/favorites" => "recipes#favorites"
  get "/my-recipes/collections" => "recipes#collections"
  get "/recipes/ingredient/:ingredient" => "recipes#ingredient"
  get '/add-to-collection' => "collections#add_to_collection"
  get '/remove-from-collection' => "collections#remove_from_collection"
  get '/about', to: "pages#about"
  get '/press', to: "pages#press"
  get '/for-blogs', to: "pages#for_blogs"
  get '/import', to: "recipes#import"

  resources :recipe_sources, path: :sources do
    resources :recipes
  end

  resources :collections

  resources :recipes do
    resources :meal_plans
    resources :likes

    member do
      get "/unlike", to: "recipes#unlike"
      get "/like", to: "recipes#like"
      get '/add-to-list', to: "recipes#add_to_list"
      get '/remove-from-list', to: "recipes#remove_from_list"
    end
  end

  resources :meal_plans do
    member do
      get "archive", to: "meal_plans#archive"
    end
  end
  root :to => "recipes#index"
end

app/views/pages/about.html.erb
<div class="hero hero--text">
  <h1>About Recidex</h1>
</div>
<div class="container container--text">
  <p>There’s a number of exciting changes happening in the food world. The local food movement is once again connecting consumers to their sources of food, and the slow food movement is bringing people back into their kitchen to prepare their own meals. At the same time, there’s been massive growth in “food content” in the past few years - independent chefs are building blogs and sharing their own recipes.</p>
  <p>Recidex.com aims to be the central hub of all of this food content. Recidex allows you to import recipes from your favorite blogs (it currently works with 150+ blogs, and we’re adding more every day). You may organize recipes into collections (e.g. “healthy breakfasts” or “quick dinners”), discover related recipes, or add several recipes to your grocery list when you’re headed to the store.</p>
  <p>Recidex.com works on your phone too - just sign in with your account to access your grocery list or recipe collections while on the run.</p>
  <p>Recidex is currently in open beta. Give the site a try - if there’s a feature you’d like added or if you’d like to discuss partnering with us, <%= link_to "reach out to us on Facebook", "https://www.facebook.com/recidex/", class: "simple-link simple-link--underline" %>. We’re excited to hear from you!</p>
</div>

app/views/pages/for_blogs.html.erb
<div class="hero hero--text">
  <h1>Using Recidex On Your Blog</h1>
</div>
<div class="container container--text" id="for-blogs-page">
  <h2>Add the Recidex Button</h2>
  <p>Adding the Recidex button to your recipe pages allows your readers to save your recipes to their recipe collections on Recidex. They'll never lose your recipe again, and they'll return to your site each time they are ready to cook.</p>
  <%= image_tag "recidex-button-collapsed.svg" %>
  <%= image_tag "recidex-button-expanded.svg" %>
  <h3>Step 1: Does Recidex support your site?</h3>
  <p>Recidex currently supports 100+ different blogs. If your site is <%= link_to "on this list", recipe_sources_path, class: "simple-link simple-link--underline" %>, then you're ready to continue to step 2.</p>
  <p>If we don't currently support your site, <%= link_to "submit a link", new_recipe_path, class: "simple-link simple-link--underline" %> to one of your recipes, and we'll add support for your site within 48 hours.</p>
  <h3>Step 2: Add this code to your site.</h3>
  <p>Copy the code below and paste it on your site wherever you'd like the button to appear.</p>
  <div class="code-snippet-block">
    <code class="code-snippet" id="recidex-button-code">
      &lt;a href="//recidex.com" id="recidex-button"&gt;&lt;/a&gt;&lt;script src="https://www.recidex.com/js/button.js"&gt;&lt;/script&gt;
    </code>
    <a href="#" class="simple-link simple-link--primary" id="copy-to-clipboard">Copy</a>
  </div>
</div>

<script type="text/javascript">
  $('#copy-to-clipboard').on('click', function(e) {
    e.preventDefault();
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val($('#recidex-button-code').text()).select();
    document.execCommand("copy");
    $temp.remove();
    $('#copy-to-clipboard').text('Copied 👍')
  })
</script>

app/views/pages/press.html.erb
<div class="hero hero--text">
  <h1>Press</h1>
</div>
<div class="container container--text" id="press-page">
  <p>Starting in the Summer of 2018, Recidex is a growing platform for foodies and chefs. If you're interested in writing about Recidex, we'd love to chat with you. Download the press kit below, or reach out to us on <%= link_to "Facebook", "https://www.facebook.com/recidex", class: "simple-link simple-link--underline" %>.</p>
  <%= link_to "Download Press Kit", "/recidex-press-kit.zip", class: "simple-link simple-link--primary" %>
  <h3>Past Mentions:</h3>
  <ul>
    <li><%= link_to "Dispatch Weekly", "http://dispatchweekly.com/2018/07/healthy-eating-healthy-life-how-recidex-can-help/", class: "simple-link simple-link--underline" %></li>
    <li><%= link_to "Style Blueprint", "https://styleblueprint.com/everyday/the-sb-hot-list-our-july-2018-favorite-things-2/", class: "simple-link simple-link--underline" %></li>
  </ul>
</div>